name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Fetch latest data
      run: |-
        curl "https://www.permits.performance.gov/api/v1/project?nid=${NID}" | jq . > raw.json
      env:
        NID: 96576
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
